# Generated by Django 4.2.7 on 2023-11-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='ahmede', max_length=50, null=True),
        ),
    ]
