# Generated by Django 4.2.7 on 2023-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_profile_email_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='main_app/static/uploads'),
        ),
        migrations.AddField(
            model_name='profile',
            name='service',
            field=models.CharField(choices=[('1', 'BAKER'), ('2', 'PHOTOGRAPHER')], default='1', max_length=1),
        ),
    ]
