# Generated by Django 4.2.7 on 2023-11-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
